CREATE TABLE "user" (
	"id" VARCHAR(100) NOT NULL UNIQUE,
	"email" VARCHAR(255) NOT NULL,
	"first_name" VARCHAR(255) NOT NULL,
	"middle_name_initial" VARCHAR(255),
	"family_name" VARCHAR(255) NOT NULL,
	"phone" VARCHAR(25) NOT NULL,
	"gender_id" INTEGER NOT NULL,
	"user_hash" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id", "phone")
);


CREATE INDEX "user_index_0"
ON "user" ("email");
CREATE INDEX "user_index_1"
ON "user" ("phone");

CREATE TABLE "gender" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"gender_desc" VARCHAR(20) NOT NULL,
	"gender_code" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "gender_index_0"
ON "gender" ("gender_code");

CREATE TABLE "country" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"country_name" VARCHAR(255) NOT NULL,
	"encoding" VARCHAR(5) NOT NULL,
	"phone_prefix" VARCHAR(3) NOT NULL,
	"country_code" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "country_index_0"
ON "country" ("country_code");

CREATE TABLE "country_state" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"country_id" INTEGER NOT NULL,
	"state_name" VARCHAR(255) NOT NULL,
	"state_code" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "country_state_index_0"
ON "country_state" ("country_id");
CREATE INDEX "country_state_index_1"
ON "country_state" ("state_code");

CREATE TABLE "address_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"address_type_desc" VARCHAR(100) NOT NULL,
	"address_type_code" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "address_type_index_0"
ON "address_type" ("address_type_code");

CREATE TABLE "address" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"address_line_one" VARCHAR(255) NOT NULL,
	"address_line_two" VARCHAR(255) NOT NULL,
	"address_line_three" VARCHAR(255),
	"country_id" INTEGER NOT NULL,
	"state_id" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE "user_address" (
	"user_id" VARCHAR(100) NOT NULL,
	"address_id" INTEGER NOT NULL,
	"address_type_id" INTEGER NOT NULL,
	"start_date" DATE NOT NULL,
	"end_date" DATE,
	PRIMARY KEY("user_id", "address_id", "start_date")
);




CREATE TABLE "family" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"creator_id" VARCHAR(100) NOT NULL,
	"family_name" VARCHAR(255) NOT NULL,
	"date_started" DATE NOT NULL,
	"date_ended" DATE,
	PRIMARY KEY("id")
);


CREATE INDEX "family_index_0"
ON "family" ("creator_id");

CREATE TABLE "family_member_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"member_type_desc" VARCHAR(255) NOT NULL,
	"member_type_code" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "member_type_index_0"
ON "family_member_type" ("member_type_code");

CREATE TABLE "family_membership" (
	"id" INTEGER,
	"family_id" INTEGER NOT NULL,
	"user_id" VARCHAR(100) NOT NULL,
	"membership_type" INTEGER NOT NULL,
	"when_joined" TIMESTAMP NOT NULL,
	"when_left" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE INDEX "family_membership_index_0"
ON "family_membership" ("user_id");
CREATE INDEX "family_membership_index_1"
ON "family_membership" ("family_id");

CREATE TABLE "subscription_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subscription_desc" VARCHAR(255) NOT NULL,
	"subscription_code" VARCHAR(25) NOT NULL,
	"cost" DECIMAL(5,2) NOT NULL,
	"frequency_id" INTEGER NOT NULL,
	"available_start_date" DATE NOT NULL,
	"available_end_date" DATE,
	PRIMARY KEY("id")
);


CREATE INDEX "subscription_type_index_0"
ON "subscription_type" ("subscription_code");

CREATE TABLE "frequency" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"frequency_desc" VARCHAR(255),
	"frequency_code" VARCHAR(25),
	PRIMARY KEY("id")
);


CREATE INDEX "frequency_index_0"
ON "frequency" ("frequency_code");

CREATE TABLE "user_subscription" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" VARCHAR(100) NOT NULL,
	"subscription_type_id" INTEGER NOT NULL,
	"start_date" DATE NOT NULL,
	"end_date" DATE,
	PRIMARY KEY("id")
);


CREATE INDEX "user_subscription_index_0"
ON "user_subscription" ("user_id");
CREATE INDEX "user_subscription_index_1"
ON "user_subscription" ("subscription_type_id");

CREATE TABLE "version_info" (
	"component" VARCHAR(255) NOT NULL UNIQUE,
	"version_number" DECIMAL(10,3) NOT NULL,
	PRIMARY KEY("component")
);




CREATE TABLE "user_share" (
	"shared_by" VARCHAR(100) NOT NULL UNIQUE,
	"shared_with" VARCHAR(100) NOT NULL,
	"share_type_id" INTEGER NOT NULL,
	"when_shared" TIMESTAMP NOT NULL,
	PRIMARY KEY("shared_by", "shared_with")
);




CREATE TABLE "share_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"share_type_desc" VARCHAR(255) NOT NULL,
	"share_type_code" VARCHAR(25) NOT NULL,
	PRIMARY KEY("id")
);



ALTER TABLE "user"
ADD FOREIGN KEY("gender_id") REFERENCES "gender"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "country"
ADD FOREIGN KEY("id") REFERENCES "country_state"("country_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "country"
ADD FOREIGN KEY("id") REFERENCES "address"("country_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "country_state"
ADD FOREIGN KEY("id") REFERENCES "address"("state_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "user_address"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "address"
ADD FOREIGN KEY("id") REFERENCES "user_address"("address_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "family_member_type"
ADD FOREIGN KEY("id") REFERENCES "family_membership"("membership_type")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "family"
ADD FOREIGN KEY("id") REFERENCES "family_membership"("family_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "family_membership"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "frequency"
ADD FOREIGN KEY("id") REFERENCES "subscription_type"("frequency_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "subscription_type"
ADD FOREIGN KEY("id") REFERENCES "user_subscription"("subscription_type_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "user_subscription"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "address_type"
ADD FOREIGN KEY("id") REFERENCES "user_address"("address_type_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "family"("creator_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "user_share"("shared_by")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "user_share"("shared_with")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "share_type"
ADD FOREIGN KEY("id") REFERENCES "user_share"("share_type_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;